excluded:
  - .build

opt_in_rules:
    - closure_spacing
    - collection_alignment
    - file_name_no_space
    - implicitly_unwrapped_optional
    - indentation_width
    - legacy_multiple
    - let_var_whitespace
    - literal_expression_end_indentation
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - vertical_whitespace_closing_braces

disabled_rules:
    - computed_accessors_order
    - cyclomatic_complexity
    - discouraged_optional_boolean
    - empty_parameters
    - file_length
    - for_where
    - force_cast
    - function_body_length
    - function_parameter_count
    - identifier_name
    - inert_defer
    - is_disjoint
    - large_tuple
    - line_length
    - nesting
    - notification_center_detachment
    - private_over_fileprivate
    - redundant_objc_attribute
    - redundant_string_enum_value
    - redundant_void_return
    - shorthand_operator
    - type_body_length
    - unused_optional_binding
    - void_return
    - empty_enum_arguments
    - let_var_whitespace
    - void_function_in_ternary
    
generic_type_name:
    min_length: 1
    max_length: 1000

trailing_whitespace:
    ignores_empty_lines: true
    
type_name:
    max_length: 1000
